# Generated by Django 4.2.13 on 2024-07-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='start_time',
            field=models.DateField(),
        ),
    ]
