# Generated by Django 4.2.13 on 2024-07-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
