# Generated by Django 5.0.7 on 2024-07-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmaterial_hiredperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaterial',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tracking'),
            preserve_default=False,
        ),
    ]
